from pathlib import Path

PROJ_ROOT = Path(__file__).resolve().parents[0]

DATA_DIR = PROJ_ROOT / "data"
EXTERNAL_DATA_DIR = DATA_DIR / "external"
INTERIM_DATA_DIR = DATA_DIR / "interim"

PROMPTS_DIR = DATA_DIR / "prompts"
TEST_PROMPTS = PROMPTS_DIR / "test_prompts.csv"
TRAIN_PROMPTS = PROMPTS_DIR / "train_prompts.csv"
VAL_PROMPTS = PROMPTS_DIR / "valid_prompts.csv"

RAW_DATA_DIR = DATA_DIR / "raw"
EXAMPLE_PROMPTS = RAW_DATA_DIR / "prompts.csv"

PROCESSED_DATA_DIR = DATA_DIR / "processed"

LLM_RESULTS_EXAMPLE_PROMPTS = PROCESSED_DATA_DIR / "llm_results.csv"
LLM_RESULTS_EXAMPLE_PROMPTS_1 = PROCESSED_DATA_DIR / "llm_results (1).csv"
LLM_RESULTS_EXAMPLE_PROMPTS_2 = PROCESSED_DATA_DIR / "llm_results (2).csv"

LLM_RESULTS_TRAIN_PROMPTS = PROCESSED_DATA_DIR / "llm_results_20260423_test.csv"
LLM_RESULTS_VAL_PROMPTS = PROCESSED_DATA_DIR / "llm_results_20260423_test.csv"
LLM_RESULTS_TEST_PROMPTS = PROCESSED_DATA_DIR / "llm_results_20260423_test.csv"

RESPONSE_FEATURES_DIR = PROCESSED_DATA_DIR / "response_features"

LLM_RESPONSES_TRAIN_FEATURES = RESPONSE_FEATURES_DIR / "llm_responses_train_features.csv"
LLM_RESPONSES_VAL_FEATURES = RESPONSE_FEATURES_DIR / "llm_responses_val_features.csv"
LLM_RESPONSES_TEST_FEATURES = RESPONSE_FEATURES_DIR / "llm_responses_test_features.csv"

LLM_RESPONSES_TRAIN_FEATURES_PLOTS_DIR = RESPONSE_FEATURES_DIR / "train_features_plots"
LLM_RESPONSES_VAL_FEATURES_PLOTS_DIR = RESPONSE_FEATURES_DIR / "val_features_plots"
LLM_RESPONSES_TEST_FEATURES_PLOTS_DIR = RESPONSE_FEATURES_DIR / "test_features_plots"
